// This file is automatically generated. Do not edit it directly.
// Placeholder mínimo: este projeto usa Firebase como backend principal;
// o client Supabase gerado aqui não está em uso em nenhuma parte do app.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
